
on:
  push:
    branches:
      - '**'

jobs:
  build_deploy_production:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }} # your  heroku api key
            heroku_app_name: ${{ secrets.HEROKU_APP_NAME }} # you aplication name
            heroku_email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
            usedocker: true
      - run: docker-compose -f docker-compose.yml up -d

